version: '3'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  api:
    build: .
    command: python app.py
    ports:
      - 5005:5000